---
title: "DATA_316_Mini_Project"
author: "Riley Fiske, Emily Liddell"
date: "2023-03-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(arm)
library(gridExtra)
library(gridtext)
```

## Data Importation

```{r}

# Variables from https://data.census.gov/mdat/#/search?ds=ACSPUMS1Y2021

mn_pums <- read.csv(file = "mn_nums.csv")

mn_pums <- mn_pums %>%
  filter(PINCP >= 0) %>%
  mutate(SEX = factor(SEX, levels=c(1,2), labels = c("Male","Female")))

```

## Data Visualization

```{r}

ggplot(data = mn_pums, aes(x = VEH)) +
  geom_histogram(stat = "count") +
  labs(title = "Histogram of Vehicles Owned per Household", x = "Vehicles Owned", y = "Count")

ggplot(data = mn_pums, aes(x = AGEP)) +
  geom_histogram() +
  labs(title = "Histogram of Age", x = "Age", y = "Count")

ggplot(data = mn_pums, aes(x = SEX)) +
  geom_histogram(stat = "count") +
  labs(title = "Histogram of Sex", x = "Sex", y = "Count")

ggplot(data = mn_pums, aes(x = WKHP)) +
  geom_histogram() +
  labs(title = "Histogram of Average Hours Worked per Week", x = "Average Hours Worked per Week", y = "Count")

plot_travel <- ggplot(data = mn_pums, aes(x = JWMNP)) +
  geom_histogram() +
  labs(title = "Travel Time to Work", x = "Travel Time to Work", y = "Count")

plot_logtravel <- ggplot(data = mn_pums, aes(x = log(JWMNP))) +
  geom_histogram() +
  labs(title = "Log Travel Time to Work", x = "Log Travel Time to Work", y = "Count")

grid.arrange(plot_travel, plot_logtravel, nrow=1, top=richtext_grob("Figure 2")) #https://community.rstudio.com/t/common-axis-title-in-grid-arrange/96353

ggplot(data = mn_pums, aes(x = ESR)) +
  geom_histogram(stat = "count") +
    labs(title = "Histogram of Employment Status", x = "Employment Status", y = "Count")

ggplot(data = mn_pums, aes(x = COW)) +
  geom_histogram(stat = "count") +
    labs(title = "Histogram of Class of Worker", x = "Class of Worker", y = "Count")

ggplot(data = mn_pums, aes(x = PINCP)) +
  geom_histogram() +
    labs(title = "Figure 1: Histogram of Income", x = "Income", y = "Count")

ggplot(data = mn_pums, aes(x = log(PINCP))) +
  geom_histogram() +
    labs(title = "Histogram of Log Income", x = "Log Income", y = "Count")

ggplot(data = mn_pums, aes(x = HINS4)) +
  geom_histogram(stat = "count") +
    labs(title = "Histogram of Medicaid Status", x = "Medicaid Status", y = "Count")

ggplot(data = mn_pums, aes(x = HHLDRRAC1P)) +
  geom_histogram(stat = "count") +
    labs(title = "Histogram of Race", x = "Race", y = "Count")


mn_pums2  <- filter(mn_pums, HHLDRRAC1P != 1)

ggplot(mn_pums2, aes(x = JWMNP, y = log(PINCP))) +
  geom_jitter(aes( color = as.factor(HHLDRRAC1P)), alpha = 0.2 ) +
  labs(title = "Figure 3: Commute Time vs. Log Income by Race", x = "Travel time to Work", y = "Log Income", color = "Race")

ggplot(mn_pums, aes(x = JWMNP, y = PINCP)) +
  geom_jitter(aes( color = as.factor(HINS4)), alpha = 0.2 ) +
    labs(title = "Figure 4: Commute Time vs. Income by Medicaid Status", x = "Travel time to Work", y = "Income", color = "Medicaid Status")

```

## Candidate Models

```{r}

#first model
mod0 <- glm(log(PINCP) ~ JWMNP + VEH + SEX_label + AGEP + WKHP, data = mn_pums)
summary(mod0)

#model we went with
mod1 <- glm(log(PINCP) ~ log(JWMNP) + VEH + SEX_label + AGEP + WKHP, data = mn_pums)
summary(mod1)

#second model
mod2 <- glm(log(PINCP) ~ log(JWMNP) + VEH + AGEP + WKHP, data = mn_pums)
summary(mod2)

#third model
mod3 <- glm(log(PINCP) ~ log(JWMNP) + VEH + WKHP, data = mn_pums)
summary(mod3)

#fourth model
mod4 <- glm(log(PINCP) ~ log(JWMNP) +  WKHP, data = mn_pums)
summary(mod4)

#fifth model
mod5 <- glm(log(PINCP) ~ WKHP, data = mn_pums)
summary(mod5)

anova(mod5, mod4, mod3,mod2,mod1, test="Chisq")
# based on these results, we chose model 1. 

```

## Final Model & Coefficient Interpretation

```{r}

mod1 <- glm(log(PINCP) ~ log(JWMNP) + VEH + SEX_label + AGEP + WKHP, data = mn_pums)
summary(mod1)

#coef interpretation

beta1 <- coef(mod1)
beta1

#Intercept
exp(beta1[1] + beta1[2]*0 + beta1[3]*0 +            beta1[5]*mean(mn_pums$AGEP) + beta1[6]*40) #We predict a female with a 0 minute commute, 0 vehicles, works 40 hours a week, and is average age to make $32418.01 annually
exp(beta1[1] + beta1[2]*0 + beta1[3]*0 + beta1[4] + beta1[5]*mean(mn_pums$AGEP) + beta1[6]*40) #We predict a male with a 0 minute commute, 0 vehicles, works 40 hours a week, and is average age to make $37618.23 annually

# Source Used for variable interpretation: https://stats.oarc.ucla.edu/sas/faq/how-can-i-interpret-log-transformed-variables-in-terms-of-percent-change-in-linear-regression/

#log(JWMNP), independent and dependent variable transformation
#We predict a one percent increase in travel time to work corresponds to a 0.09% increase in annual income

#VEH, dependent variable transformation
(exp(beta1[3]) - 1) * 100 #We predict a difference in one vehicle corresponds to a decrease in annual income by 3.12%

#AGEP, dependent variable transformation
(exp(beta1[5]) - 1) * 100 #We predict a difference in one year in age corresponds to an increase in annual income by 1.95%

#WKHP, dependent variable transformation
(exp(beta1[6]) - 1) * 100 #We predict a difference in one hour worked on average per week corresponds to an increase in annual income by 3.73%


```

## Variable Visualizations

```{r}

beta1 <- coef(mod1)
beta1

# Visualization with everything held constant but JWMNP
func.1.JWMNP_male <- function(x){beta1[[1]]+beta1[[2]]*x + beta1[[3]]*mean(mn_pums$VEH) + beta1[[4]] + beta1[[5]]*mean(mn_pums$AGEP) + beta1[[6]]*mean(mn_pums$WKHP)} #Female
func.1.JWMNP_female <- function(x){beta1[[1]]+beta1[[2]]*x + beta1[[3]]*mean(mn_pums$VEH) +            + beta1[[5]]*mean(mn_pums$AGEP) + beta1[[6]]*mean(mn_pums$WKHP)} #Male
plot_predlogJWMNP <- ggplot(mn_pums, aes(x = log(JWMNP))) +
  geom_jitter(aes(y=log(PINCP)), width = 0.05, height = 0.05) +
  geom_function(fun = func.1.JWMNP_female, color="red") +
  geom_function(fun = func.1.JWMNP_male, color = "blue") +
  labs(title = "Figure 7: Log Travel Time to Work vs. Predicted Income", x = "Log Travel Time", y = "Predicted Income")

# Visualization with everything held constant but VEH
func.1.VEH_male <- function(x){beta1[[1]]+beta1[[2]]*mean(log(mn_pums$JWMNP)) + beta1[[3]]*x + beta1[[4]] + beta1[[5]]*mean(mn_pums$AGEP) + beta1[[6]]*mean(mn_pums$WKHP)} #Female
func.1.VEH_female <- function(x){beta1[[1]]+beta1[[2]]*mean(log(mn_pums$JWMNP))   + beta1[[3]]*x +            + beta1[[5]]*mean(mn_pums$AGEP) + beta1[[6]]*mean(mn_pums$WKHP)} #Male
plot_predVEH <- ggplot(mn_pums, aes(x = VEH)) +
  geom_jitter(aes(y = log(PINCP)), width = 0.25, height = 0.05) +
  geom_function(fun = func.1.VEH_female, color="red") +
  geom_function(fun = func.1.VEH_male, color = "blue") +
  labs(title = "Figure 8: Household Vehicles Owned vs. Predicted Income", x = "Number of Vehicles", y = "Predicted Income")

# Visualization with everything held constant but WKHP
func.1.WKHP_male <- function(x){beta1[[1]]+beta1[[2]]*mean(log(mn_pums$JWMNP)) + beta1[[3]]*mean(mn_pums$VEH) + beta1[[4]] + beta1[[5]]*mean(mn_pums$AGEP) + beta1[[6]]*x} #Female
func.1.WKHP_female <- function(x){beta1[[1]]+beta1[[2]]*mean(log(mn_pums$JWMNP))   + beta1[[3]]*mean(mn_pums$VEH) +            + beta1[[5]]*mean(mn_pums$AGEP) + beta1[[6]]*x} #Male
plot_predWKHP <- ggplot(mn_pums, aes(x = WKHP)) +
  geom_jitter(aes(y=log(PINCP)), width = 0, height = 0.05) +
  geom_function(fun = func.1.WKHP_female, color="red") +
  geom_function(fun = func.1.WKHP_male, color = "blue") +
  labs(title = "Average Hours Worked per Week", x = "Average Hours Worked per Week", y = "Predicted Income")

# Visualization with everything held constant but AGEP
func.1.WKHP_male <- function(x){beta1[[1]]+beta1[[2]]*mean(log(mn_pums$JWMNP)) + beta1[[3]]*mean(mn_pums$VEH) + beta1[[4]] + beta1[[5]]*x + beta1[[6]]*mean(mn_pums$WKHP)} #Female
func.1.WKHP_female <- function(x){beta1[[1]]+beta1[[2]]*mean(log(mn_pums$JWMNP))   + beta1[[3]]*mean(mn_pums$VEH) +            + beta1[[5]]*x + beta1[[6]]*mean(mn_pums$WKHP)} #Male
plot_predage <- ggplot(mn_pums, aes(x = AGEP)) +
  geom_jitter(aes(y=log(PINCP)), width = 0, height = 0.05) +
  geom_function(fun = func.1.WKHP_female, color="red") +
  geom_function(fun = func.1.WKHP_male, color = "blue") +
  labs(title = "Age vs. Predicted Income", x = "Age", y = "Predicted Income")

plot_predlogJWMNP

plot_predVEH

grid.arrange(plot_predWKHP, plot_predage, nrow = 1, top=richtext_grob("Figure 9"))

```

## Final Model Analysis

```{r}

mn_pums$pred.1 <- predict(mod1, type = "response")
mn_pums$res.1 <- log(mn_pums$PINCP) - mn_pums$pred.1
sigma <- sigma(mod1)
ggplot(mn_pums, aes(x=pred.1, y=res.1)) +
  geom_point(alpha = 0.1) +
  geom_hline(yintercept=0, color = "red") +
  geom_hline(yintercept= c(sigma, -sigma), color="red", linetype="dashed") +
  labs(title= "Figure 5: Predicted Annual Income vs. Residuals",x = "Predicted Personal Income", y = "Residuals")

ggplot(mn_pums, aes(x = pred.1, y = log(PINCP))) +
  geom_jitter(alpha = 0.1) +
  geom_abline(color = "red") +
  labs(title = "Figure 6: Predicted Income vs. Actual Income", x = "Predicted Income", y = "Actual Income")
  
```